### ISSUE TITLE
Video recording issues

### ISSUE THREAD

**Issue by seebi** [GeoKnow/Facete#1]
Service: http://test.linkedgeodata.org/browser/
- tune database for video
- budget line labels!!!

General issues
- show all labels or local name
- replace red/yellow marker with more nice markers
- config tuning for better facets
- click on background should close open windows

Script:
- zoom to germany
- show all cities with subventions
- filter by year
- click on a city and show subventions for city
- filter by business line = _disaster_
- show all disaster related subventions

MII issues (not shown)
- niceup orange overlay box (Mass Instance Indicate = MII)
- MII should be clickable (click to zoom)
- MII should be coverable (switch color)

other issues:
- left tab should show labels
- rename `Start` tab to `Config`
- switch Config and Places Tab

**Comment by Aklakan** [comment]
this is done for a loooong time already.
